<a href="https://colab.research.google.com/github/anantmehta33/PowerPlant/blob/main/Combined_power_plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A combined-cycle power plant is an electrical power plant in which a Gas Turbine (GT) and a Steam Turbine (ST) are used in combination to produce more electrical energy from the same fuel than that would be possible from a single cycle power plant.

The gas turbine compresses air and mixes it with a fuel heated to a very high temperature. The hot air-fuel mixture moves through the blades, making them spin. The fast-spinning gas turbine drives a generator to generate electricity. The exhaust (waste) heat escaped through the exhaust stack of the gas turbine is utilized by a Heat Recovery Steam Generator (HSRG) system to produce steam that spins a steam turbine. This steam turbine drives a generator to produce additional electricity. CCCP is assumed to produce 50% more energy than a single power plant.



The objective is to create a data model that predicts the net hourly electrical energy output (EP) of the plant using available hourly average ambient variables.

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__#tensorflow 2.0

'2.7.0'

Data preprocessing

In [ ]:
data=pd.read_excel('dataset.xlsx')
print(data.shape)

(9568, 5)


In [ ]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


splitting data 

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

building the neural network

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,))# for regression we need no act func as linearity is needed

Training and Compiling ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)#training model on training set
#reducing loss epoch by epoch 

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 204668.3281
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 182912.0625
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 114451.7656
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 44771.0391
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 21639.4355
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 16043.7881
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 11748.0566
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 7924.3931
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 4811.2373
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 2644.0679
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 1354.4465
Epoch 12/100
240/240 [==============================]

predicting results

In [ ]:
Y_answer=ann.predict(X_test)#y_answer has the pred to Y_test
np.set_printoptions(precision=2)

Y_answer vs Y_test

In [ ]:
Y_answer.reshape(-1,1)
print(Y_answer)#predicted

[[436.88]
 [458.06]
 [462.58]
 ...
 [469.21]
 [441.83]
 [461.72]]


In [ ]:
print(Y_test)#real

[431.23 460.01 461.14 ... 473.26 438.   463.28]
